# Where should we write the GIF?
Output delete.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 16
Set Width 1200
Set Height 500

Hide
Type "wakey"
Enter
Sleep 5s
Tab
Sleep 5s

# Create a new group
Type "c"
Type "Demo Group"
Enter
Type "demo-01, demo-02"
Enter
Enter

Show

# Go to device you want to delete
Sleep 3s
Type "j"
Sleep 3s

# Delete device
Type "d"
Sleep 2s
Right
Sleep 1s
Left
Sleep 2s
Type "y"
Sleep 3s